language: erlang

otp_release:
  - R16B03
  - R15B01

services:
  - riak

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get -qq install libexpat1-dev libyaml-dev libpam0g-dev

before_script:
  - mysql -u root -e "CREATE USER 'ejabberd_test'@'localhost' IDENTIFIED BY 'ejabberd_test';"
  - mysql -u root -e "CREATE DATABASE ejabberd_test;"
  - mysql -u root -e "GRANT ALL ON ejabberd_test.* TO 'ejabberd_test'@'localhost';"
  - psql -U postgres -c "CREATE USER ejabberd_test WITH PASSWORD 'ejabberd_test';"
  - psql -U postgres -c "CREATE DATABASE ejabberd_test;"
  - psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE ejabberd_test TO ejabberd_test;"

script:
  - ./autogen.sh
  - ./configure --enable-all --disable-odbc --disable-elixir
  - make xref
  - ERL_LIBS=$PWD make test
  - grep -q 'TEST COMPLETE, \([[:digit:]]*\) ok, .* of \1 ' logs/raw.log

after_script:
  - find logs -name suite.log -exec cat '{}' ';'

after_failure:
  - find logs -name ejabberd.log -exec cat '{}' ';'

notifications:
  email: false
